import Link from "next/link";

export const metadata = {
  title: "Welcome",
  description: "Generated by AY Salaad",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Welcome to Holiday social</h1>
          <nav>
            <button>
              <Link href="/">Home</Link>
            </button>
            <button>
              <Link href="/posts">Posts</Link>
            </button>
            <button>
              <Link href="/about">About</Link>
            </button>
            <button>
              <Link href="/newposts">New posts</Link>
            </button>
            <button>
              <Link href="/singleposts">Single post</Link>
            </button>
          </nav>
          <img src="https://th.bing.com/th/id/OIP.V0aSFXXBCJ1tvyouH8bdlgHaE8?w=267&h=180&c=7&r=0&o=5&dpr=2&pid=1.7" placeholder="blur"/>
          <h2>Post your favourite holiday destination
            <button id="Post">Add post</button>
            <button id="Delete">Delete post</button>
            <button id="Edit">Edit post</button>
          </h2>
          <h3>
            <p>Comment on post</p>
            <button id="Comment">Comment</button>
          </h3>
        </header>
        <footer>&copy;Life is good</footer>
        {children}
      </body>
    </html>
  );
}